# -*- coding: utf-8 -*-
"""p103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xb7OV-F6Gk_EAkj8cvTPBBA8dpYBX7Aj
"""

from google.colab import files 
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv("covid_chart.csv")
fig=px.scatter(df,x="date",y="cases",color="country")
fig.show()